variable subnet_id {}
variable vpc_id {}
variable security_group_id {}
variable AMAZON_SES_ADDRESS {}
variable AMAZON_SES_DOMAIN {}
variable MAILER_FROM_ADDRESS {}
variable SMTP_PROVIDER {}
variable email {}
variable cluster_name {}
variable region {}
variable domain {}
variable hosted_zone_id {}
variable cluster_id {}
variable kms_key_id {}
variable service_registry_dns_namespace_id {}
