variable DATABASE_URL {}
variable POSTGRES_USER {}
variable AMAZON_SES_ADDRESS {}
variable AMAZON_SES_DOMAIN {}
variable AMAZON_SES_PASSWORD {}
variable AMAZON_SES_USERNAME {}
variable MAILER_FROM_ADDRESS {}
variable SECRET_KEY_BASE {}
variable SMTP_PROVIDER {}
variable email {}
variable cluster_name {}
variable region {}
variable domain {}
variable hosted_zone_id {}
variable cluster_id {}
